version: '3.9'

services:
  api:
    build: .
    ports:
      - 4000:8000
      - 9229:9229 # debugger port

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    environment:
       port: 8000


